name: playstore
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  orientation: ^1.3.0
  nb_utils: ^4.6.25
  http: ^0.13.5
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  test: ^1.21.4

flutter_icons:
  ios: true
  image_path: "assets/ps-logo.png"
  android: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/games/pvz/pvz-cover.png
    - assets/games/pvz/pvz-profile.png
    - assets/games/cc/cc-profile.png
    - assets/games/cc/cc-cover.png
    - assets/games/coc/coc-profile.jpg
    - assets/games/coc/coc-cover.png
    - assets/games/ml/ml-profile.png
    - assets/games/ml/ml-cover.png
    - assets/games/rbx/rbx-profile.png
    - assets/games/rbx/rbx-cover.png
    - assets/games/chss/chss-profile.png
    - assets/games/chss/chss-cover.png

    - assets/games/kids/ytk/ytk-profile.png
    - assets/games/kids/cg/cg-profile.png
    - assets/games/kids/kgt/kgt-profile.png
    - assets/games/kids/sp/sp-profile.png
    - assets/games/kids/mt/mt-profile.png

    - assets/games/premium/mc/mc-profile.png
    - assets/games/premium/te/te-profile.png
    - assets/games/premium/stv/stv-profile.png
    - assets/games/premium/gta/gta-profile.png
    - assets/games/premium/ds/ds-profile.png

    - assets/apps/for you/fb/fb-profile.png
    - assets/apps/for you/ig/ig-profile.png
    - assets/apps/for you/sp/sp-profile.png
    - assets/apps/for you/tw/tw-profile.png
    - assets/apps/for you/nx/nx-profile.png

    - assets/icons/icon-action.png
    - assets/icons/icon-adventure.png
    - assets/icons/icon-arcade.png
    - assets/icons/icon-board.png
    - assets/icons/icon-card.png
    - assets/icons/icon-casino.png
    - assets/icons/icon-casual.png
    - assets/icons/icon-educational.png
    - assets/icons/icon-music.png
    - assets/icons/icon-puzzle.png
    - assets/icons/icon-racing.png
    - assets/icons/icon-roleplaying.png
    - assets/icons/icon-simulation.png
    - assets/icons/icon-sports.png
    - assets/icons/icon-strategy.png
    - assets/icons/icon-trivia.png
    - assets/icons/icon-word.png

    - assets/kids.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
